# =============================================================
# CodeCompass Analyzer - Repository Intelligence Engine
# Generated by IBM watsonx.ai (Bob) | IBM Build Lab Hackathon
# Powered by IBM Granite | github.com/IBM/granite-code-models
# =============================================================

import requests
import os
import re
from collections import Counter
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")

def get_repo_tree(owner: str, repo: str) -> list:
    """Fetch the full file tree of a GitHub repository."""
    headers = {"Authorization": f"token {GITHUB_TOKEN}"} if GITHUB_TOKEN else {}
    url = f"https://api.github.com/repos/{owner}/{repo}/git/trees/HEAD?recursive=1"
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        return []
    tree = response.json().get("tree", [])
    return [item["path"] for item in tree if item["type"] == "blob"]

def get_repo_metadata(owner: str, repo: str) -> dict:
    """Fetch repository metadata from GitHub API."""
    headers = {"Authorization": f"token {GITHUB_TOKEN}"} if GITHUB_TOKEN else {}
    url = f"https://api.github.com/repos/{owner}/{repo}"
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            data = response.json()
            return {
                "description": data.get("description", ""),
                "language": data.get("language", ""),
                "stars": data.get("stargazers_count", 0),
                "forks": data.get("forks_count", 0),
                "topics": data.get("topics", []),
                "created_at": data.get("created_at", ""),
                "updated_at": data.get("updated_at", ""),
                "size": data.get("size", 0),
                "open_issues": data.get("open_issues_count", 0)
            }
    except:
        pass
    return {}

def get_file_content(owner: str, repo: str, path: str) -> str:
    """Fetch content of a specific file from GitHub."""
    headers = {"Authorization": f"token {GITHUB_TOKEN}"} if GITHUB_TOKEN else {}
    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        return ""
    import base64
    content = response.json().get("content", "")
    try:
        return base64.b64decode(content).decode("utf-8", errors="ignore")
    except:
        return ""

def analyze_file_structure(file_list: list) -> dict:
    """Analyze repository structure and patterns."""
    extensions = Counter()
    directories = set()
    
    for file_path in file_list:
        # Count extensions
        if "." in file_path:
            ext = file_path.split(".")[-1]
            extensions[ext] += 1
        
        # Track directories
        if "/" in file_path:
            dirs = file_path.split("/")[:-1]
            for i in range(len(dirs)):
                directories.add("/".join(dirs[:i+1]))
    
    # Detect patterns
    has_tests = any("test" in f.lower() for f in file_list)
    has_docs = any("doc" in f.lower() or "readme" in f.lower() for f in file_list)
    has_ci = any(".github" in f or ".gitlab" in f or "jenkins" in f.lower() for f in file_list)
    has_docker = any("docker" in f.lower() for f in file_list)
    has_api = any("api" in f.lower() or "endpoint" in f.lower() for f in file_list)
    has_frontend = any(ext in ["js", "jsx", "ts", "tsx", "vue", "html", "css"] for ext in extensions.keys())
    has_backend = any(ext in ["py", "java", "go", "rb", "php"] for ext in extensions.keys())
    
    return {
        "extensions": dict(extensions.most_common(10)),
        "total_directories": len(directories),
        "has_tests": has_tests,
        "has_docs": has_docs,
        "has_ci": has_ci,
        "has_docker": has_docker,
        "has_api": has_api,
        "has_frontend": has_frontend,
        "has_backend": has_backend,
        "top_directories": sorted(list(directories))[:15]
    }

def extract_dependencies(file_list: list, owner: str, repo: str) -> dict:
    """Extract dependencies from various package files."""
    deps = {"languages": [], "frameworks": [], "tools": []}
    
    # Check for dependency files
    dep_files = {
        "requirements.txt": "Python",
        "package.json": "JavaScript/Node.js",
        "Gemfile": "Ruby",
        "pom.xml": "Java/Maven",
        "build.gradle": "Java/Gradle",
        "go.mod": "Go",
        "Cargo.toml": "Rust",
        "composer.json": "PHP"
    }
    
    for dep_file, lang in dep_files.items():
        if any(dep_file in f for f in file_list):
            deps["languages"].append(lang)
            
            # Try to read the file
            matching_files = [f for f in file_list if dep_file in f]
            if matching_files:
                content = get_file_content(owner, repo, matching_files[0])
                if content:
                    # Extract framework names
                    if "django" in content.lower():
                        deps["frameworks"].append("Django")
                    if "flask" in content.lower():
                        deps["frameworks"].append("Flask")
                    if "fastapi" in content.lower():
                        deps["frameworks"].append("FastAPI")
                    if "react" in content.lower():
                        deps["frameworks"].append("React")
                    if "vue" in content.lower():
                        deps["frameworks"].append("Vue.js")
                    if "angular" in content.lower():
                        deps["frameworks"].append("Angular")
                    if "express" in content.lower():
                        deps["frameworks"].append("Express.js")
                    if "spring" in content.lower():
                        deps["frameworks"].append("Spring")
    
    return deps

def get_key_files(file_list: list) -> list:
    """Intelligently pick the most important files to analyze."""
    priority_patterns = [
        (r"README\.(md|txt|rst)", 100),  # Documentation
        (r"(main|app|index|server)\.(py|js|ts|go|java)", 90),  # Entry points
        (r"(requirements|package|Gemfile|pom|build\.gradle|go\.mod|Cargo)\.(txt|json|lock|xml|toml)", 85),  # Dependencies
        (r"(config|settings|\.env\.example)\.(py|js|json|yaml|yml|toml)", 80),  # Configuration
        (r"Dockerfile", 75),  # Containerization
        (r"(docker-compose|kubernetes|k8s)\.(yml|yaml)", 70),  # Orchestration
        (r"\.github/workflows/.*\.yml", 65),  # CI/CD
        (r"(models|schema|database)\.(py|js|ts|sql)", 60),  # Data models
        (r"(routes|controllers|views|api)\.(py|js|ts)", 55),  # API/Routes
        (r"(test_|_test\.|\.test\.|\.spec\.)", 50),  # Tests
    ]
    
    scored_files = []
    for file_path in file_list:
        score = 0
        for pattern, points in priority_patterns:
            if re.search(pattern, file_path, re.IGNORECASE):
                score += points
        
        # Bonus for files in root or important directories
        if "/" not in file_path or file_path.count("/") == 1:
            score += 20
        
        if score > 0:
            scored_files.append((file_path, score))
    
    # Sort by score and take top files
    scored_files.sort(key=lambda x: x[1], reverse=True)
    key_files = [f[0] for f in scored_files[:15]]
    
    return key_files

def build_context(owner: str, repo: str, file_list: list) -> str:
    """Build an intelligent context string with deep analysis."""
    # Get repository metadata
    metadata = get_repo_metadata(owner, repo)
    
    # Analyze structure
    structure = analyze_file_structure(file_list)
    
    # Extract dependencies
    dependencies = extract_dependencies(file_list, owner, repo)
    
    # Get key files
    key_files = get_key_files(file_list)
    
    # Build comprehensive context
    context = f"""# Repository Analysis: {owner}/{repo}

## Repository Metadata
- Description: {metadata.get('description', 'N/A')}
- Primary Language: {metadata.get('language', 'N/A')}
- Stars: {metadata.get('stars', 0)} | Forks: {metadata.get('forks', 0)}
- Topics: {', '.join(metadata.get('topics', [])) or 'None'}
- Size: {metadata.get('size', 0)} KB
- Open Issues: {metadata.get('open_issues', 0)}

## Structure Analysis
- Total Files: {len(file_list)}
- Total Directories: {structure['total_directories']}
- File Types: {', '.join([f"{ext} ({count})" for ext, count in list(structure['extensions'].items())[:5]])}

## Project Characteristics
- Has Tests: {'✓' if structure['has_tests'] else '✗'}
- Has Documentation: {'✓' if structure['has_docs'] else '✗'}
- Has CI/CD: {'✓' if structure['has_ci'] else '✗'}
- Has Docker: {'✓' if structure['has_docker'] else '✗'}
- Has API Layer: {'✓' if structure['has_api'] else '✗'}
- Architecture: {'Full-stack' if structure['has_frontend'] and structure['has_backend'] else 'Frontend' if structure['has_frontend'] else 'Backend' if structure['has_backend'] else 'Unknown'}

## Technology Stack
- Languages: {', '.join(dependencies['languages']) or 'Detecting...'}
- Frameworks: {', '.join(dependencies['frameworks']) or 'Analyzing...'}

## Key Directories
{chr(10).join(['- ' + d for d in structure['top_directories'][:10]])}

## File Tree Sample (First 50 files)
{chr(10).join(file_list[:50])}

## Key File Contents Analysis
"""
    
    # Add key file contents
    for idx, file_path in enumerate(key_files, 1):
        content = get_file_content(owner, repo, file_path)
        if content:
            # Intelligently truncate based on file type
            max_length = 2500 if any(x in file_path.lower() for x in ['readme', 'doc']) else 2000
            truncated_content = content[:max_length]
            if len(content) > max_length:
                truncated_content += "\n... (truncated)"
            
            context += f"\n\n### File {idx}: {file_path}\n```\n{truncated_content}\n```"
    
    return context

def parse_github_url(url: str) -> tuple:
    """Extract owner and repo from a GitHub URL."""
    url = url.rstrip("/").replace("https://github.com/", "").replace("http://github.com/", "")
    if url.endswith(".git"):
        url = url[:-4]
    parts = url.split("/")
    if len(parts) >= 2:
        return parts[0], parts[1]
    return None, None

def smart_audit(owner: str, repo: str, file_list: list) -> dict:
    """Perform smart audit of repository to detect quick wins and calculate scores."""
    quick_wins = []
    
    # Helper to check if any file matches patterns
    def has_file(patterns):
        return any(any(p in f.lower() for p in patterns) for f in file_list)
    
    def has_exact_file(names):
        return any(f in file_list or f.lower() in [x.lower() for x in file_list] for f in names)
    
    # Check for README
    if not has_exact_file(['README.md', 'README.rst', 'README.txt', 'README']):
        quick_wins.append({
            "title": "Add a README",
            "description": "Projects without a README are hard to onboard to.",
            "difficulty": "Easy",
            "time": "10 min",
            "file": "README.md"
        })
    
    # Check for .gitignore
    if not has_exact_file(['.gitignore']):
        quick_wins.append({
            "title": "Add .gitignore",
            "description": "Prevent committing secrets and build artifacts.",
            "difficulty": "Easy",
            "time": "5 min",
            "file": ".gitignore"
        })
    
    # Check for test files
    test_patterns = ['test_', '_test.', '.test.', '.spec.']
    if not has_file(test_patterns):
        quick_wins.append({
            "title": "No tests found",
            "description": "Add unit tests to prevent regressions.",
            "difficulty": "Medium",
            "time": "2–4 hours",
            "file": "tests/"
        })
    
    # Check for Dockerfile
    if not has_file(['dockerfile']):
        quick_wins.append({
            "title": "Add Dockerfile",
            "description": "Containerize for consistent deployments.",
            "difficulty": "Medium",
            "time": "30 min",
            "file": "Dockerfile"
        })
    
    # Check for CI/CD
    ci_patterns = ['.github/workflows', '.gitlab-ci.yml', '.circleci', 'jenkinsfile']
    if not has_file(ci_patterns):
        quick_wins.append({
            "title": "No CI/CD pipeline",
            "description": "Automate testing and deployment.",
            "difficulty": "Medium",
            "time": "1 hour",
            "file": ".github/workflows/"
        })
    
    # Check for LICENSE
    if not has_exact_file(['LICENSE', 'LICENSE.md', 'LICENSE.txt']):
        quick_wins.append({
            "title": "Add a LICENSE",
            "description": "Required for open source use.",
            "difficulty": "Easy",
            "time": "2 min",
            "file": "LICENSE"
        })
    
    # Check for committed .env file
    if has_exact_file(['.env']):
        quick_wins.append({
            "title": "Possible .env committed",
            "description": "Never commit .env files with real secrets.",
            "difficulty": "Easy",
            "time": "5 min",
            "file": ".env"
        })
    
    # Check for dependency manifest
    dep_files = ['requirements.txt', 'package.json', 'go.mod', 'Cargo.toml', 'pom.xml', 'Gemfile']
    if not has_exact_file(dep_files):
        quick_wins.append({
            "title": "Missing dependency manifest",
            "description": "Document your dependencies explicitly.",
            "difficulty": "Easy",
            "time": "15 min",
            "file": "requirements.txt"
        })
    
    # Check for flat structure (>30% files in root)
    root_files = [f for f in file_list if '/' not in f]
    if len(file_list) > 0 and len(root_files) / len(file_list) > 0.3:
        quick_wins.append({
            "title": "Flat structure — consider organizing",
            "description": "Group files into src/, utils/, tests/ folders.",
            "difficulty": "Easy",
            "time": "30 min",
            "file": "/"
        })
    
    # Calculate scores
    total_files = len(file_list) if file_list else 1
    
    # Test score: (number of test files / total files) * 10, capped at 10
    test_files = [f for f in file_list if any(p in f.lower() for p in test_patterns)]
    test_score = min(10.0, round((len(test_files) / total_files) * 10, 1))
    
    # DevOps score: +2.5 for each (Dockerfile, CI/CD, .env.example, Makefile)
    devops_score = 0.0
    if has_file(['dockerfile']):
        devops_score += 2.5
    if has_file(ci_patterns):
        devops_score += 2.5
    if has_exact_file(['.env.example', '.env.sample']):
        devops_score += 2.5
    if has_exact_file(['Makefile', 'makefile']):
        devops_score += 2.5
    devops_score = round(min(10.0, devops_score), 1)
    
    # Docs score: +4 README, +3 /docs folder, +2 CHANGELOG, +1 CONTRIBUTING
    docs_score = 0.0
    if has_exact_file(['README.md', 'README.rst', 'README.txt', 'README']):
        docs_score += 4.0
    if has_file(['docs/']):
        docs_score += 3.0
    if has_exact_file(['CHANGELOG.md', 'CHANGELOG.rst', 'CHANGELOG.txt', 'CHANGELOG']):
        docs_score += 2.0
    if has_exact_file(['CONTRIBUTING.md', 'CONTRIBUTING.rst', 'CONTRIBUTING.txt']):
        docs_score += 1.0
    docs_score = round(min(10.0, docs_score), 1)
    
    # Structure score: start at 10, -2 for each missing (tests, docs, ci, docker, license)
    structure_score = 10.0
    if not has_file(test_patterns):
        structure_score -= 2.0
    if not has_exact_file(['README.md', 'README.rst', 'README.txt', 'README']):
        structure_score -= 2.0
    if not has_file(ci_patterns):
        structure_score -= 2.0
    if not has_file(['dockerfile']):
        structure_score -= 2.0
    if not has_exact_file(['LICENSE', 'LICENSE.md', 'LICENSE.txt']):
        structure_score -= 2.0
    structure_score = round(max(0.0, structure_score), 1)
    
    # Security score: start at 10, -4 if .env committed, -3 if no .gitignore, -3 if secrets/credentials in root
    security_score = 10.0
    if has_exact_file(['.env']):
        security_score -= 4.0
    if not has_exact_file(['.gitignore']):
        security_score -= 3.0
    secret_files = [f for f in root_files if 'secret' in f.lower() or 'credential' in f.lower()]
    if secret_files:
        security_score -= 3.0
    security_score = round(max(0.0, security_score), 1)
    
    return {
        "quick_wins": quick_wins,
        "scores": {
            "test_score": test_score,
            "devops_score": devops_score,
            "docs_score": docs_score,
            "structure_score": structure_score,
            "security_score": security_score
        }
    }