# =============================================================
# CodeCompass - AI-Powered Repository Intelligence
# Generated by IBM watsonx.ai (Bob) | IBM Bob Dev Day Hackathon
# Model: ibm/granite-3-8b-instruct
# Platform: IBM Cloud | Code Engine
# =============================================================
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
