# =============================================================
# CodeCompass - AI-Powered Repository Intelligence
# Generated by IBM watsonx.ai (Bob) | IBM Bob Dev Day Hackathon
# Model: ibm/granite-13b-chat-v2
# Platform: IBM Cloud | watsonx.ai
# =============================================================

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
import httpx
import os
from analyzer import get_repo_tree, build_context, parse_github_url, smart_audit, get_file_content
from dotenv import load_dotenv

load_dotenv()

# FastAPI application — scaffolded by IBM watsonx.ai
app = FastAPI(title="CodeCompass API", description="Powered by IBM watsonx.ai Granite")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

WATSONX_API_KEY = os.getenv("WATSONX_API_KEY", "")
WATSONX_PROJECT_ID = os.getenv("WATSONX_PROJECT_ID", "")
WATSONX_URL = "https://us-south.ml.cloud.ibm.com/ml/v1/text/generation?version=2023-05-29"

class RepoRequest(BaseModel):
    github_url: str

class QuestionRequest(BaseModel):
    github_url: str
    question: str

async def get_iam_token():
    """Exchange IBM API key for IAM access token."""
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                "https://iam.cloud.ibm.com/identity/token",
                data={
                    "grant_type": "urn:ibm:params:oauth:grant-type:apikey",
                    "apikey": WATSONX_API_KEY
                },
                headers={"Content-Type": "application/x-www-form-urlencoded"}
            )
            return response.json().get("access_token", "")
    except Exception:
        return ""

def generate_local_analysis(prompt: str, context: str = "", scores: dict = None) -> str:
    """Fallback analysis using context when watsonx is unavailable."""
    if "Architecture" in prompt or "analyze" in prompt.lower():
        lines = context.split('\n')
        lang = next((l.split(':')[1].strip() for l in lines if 'Primary Language:' in l), 'Multiple')
        has_tests = '✓' in next((l for l in lines if 'Has Tests:' in l), '')
        has_docker = '✓' in next((l for l in lines if 'Has Docker:' in l), '')
        has_ci = '✓' in next((l for l in lines if 'Has CI/CD:' in l), '')
        arch_type = next((l.split(':')[1].strip() for l in lines if 'Architecture:' in l), 'Unknown')

        s = scores or {}
        avg = round(
            s.get('structure_score', 0) * 0.30 +
            s.get('test_score',      0) * 0.25 +
            s.get('docs_score',      0) * 0.20 +
            s.get('devops_score',    0) * 0.15 +
            s.get('security_score',  0) * 0.10
        , 1) if s else 0

        return f"""## Architecture Summary
This is a **{arch_type}** application built primarily with **{lang}**.

## Key Components
- **Entry Points**: Core application files handling initialization and routing
- **Business Logic**: Domain-specific modules implementing core functionality
- **Configuration**: Environment settings and application configuration
- **Data Layer**: Models, schemas, and database interactions
- **Testing Suite**: {'Comprehensive test coverage' if has_tests else 'Tests not detected — consider adding them'}

## Tech Stack
- **Primary Language**: {lang}
- **Architecture**: {arch_type}
- **DevOps**: {'Docker + ' if has_docker else ''}{'CI/CD pipeline' if has_ci else 'No CI/CD detected'}

## Onboarding Guide
1. Review README and setup instructions
2. Check package files for dependencies
3. Explore main application files
4. {'Run the existing test suite' if has_tests else 'Set up your development environment'}

## Complexity Assessment
- **Overall Score**: {avg}/10 (computed from test coverage, DevOps, docs, structure, security)
- **Maintainability**: {'Good' if avg >= 6 else 'Needs improvement'}
- **Recommendation**: {'Well-structured project — focus on CI/CD and containerization.' if has_tests else 'Add tests and a CI/CD pipeline to improve reliability.'}"""
    else:
        return "Based on the repository analysis, this codebase implements the requested functionality through well-organized modules. Review the key files in the architecture summary for implementation details."

def strip_emojis(text: str) -> str:
    import re
    return re.sub(
        r'[\U00010000-\U0010ffff'
        r'\U0001F300-\U0001F9FF'
        r'\U00002702-\U000027B0'
        r'\U0000FE00-\U0000FE0F'
        r'☀-⛿✀-➿]+',
        '', text
    ).strip()

async def ask_watsonx(prompt: str, context: str = "", scores: dict = None) -> str:
    """Send prompt to watsonx.ai with enhanced parameters."""
    try:
        token = await get_iam_token()
        if not token:
            return generate_local_analysis(prompt, context, scores)

        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }
        payload = {
            "model_id": "ibm/granite-3-8b-instruct",
            "input": prompt,
            "parameters": {
                "max_new_tokens": 1200,
                "temperature": 0.4,
                "top_p": 0.9,
                "top_k": 50,
                "repetition_penalty": 1.1
            },
            "project_id": WATSONX_PROJECT_ID
        }
        async with httpx.AsyncClient(timeout=90) as client:
            response = await client.post(WATSONX_URL, json=payload, headers=headers)
            result = response.json()
            generated = result.get("results", [{}])[0].get("generated_text", "")
            if not generated or len(generated.strip()) < 50:
                return generate_local_analysis(prompt, context, scores)
            return strip_emojis(generated)
    except Exception:
        return generate_local_analysis(prompt, context, scores)

@app.get("/")
def index():
    return FileResponse("index.html")

@app.post("/analyze")
async def analyze_repo(request: RepoRequest):
    """Analyze a GitHub repository with deep intelligence."""
    owner, repo = parse_github_url(request.github_url)
    if not owner:
        return {"error": "Invalid GitHub URL"}

    file_list = get_repo_tree(owner, repo)
    if not file_list:
        return {"error": "Could not fetch repository. Check URL or token."}

    context = build_context(owner, repo, file_list)

    prompt = f"""You are CodeCompass, an elite software architect and code analyst with deep expertise across all programming paradigms, frameworks, and architectural patterns.

Your task is to provide a comprehensive, insightful analysis of this repository that goes beyond surface-level observations.

{context}

Provide a detailed, professional analysis with these sections:

## ARCHITECTURE OVERVIEW
Describe the architectural pattern (MVC, microservices, monolithic, etc.), design philosophy, and how components interact. Be specific about the architecture style and its benefits for this use case.

## KEY COMPONENTS & RESPONSIBILITIES
List the 5-7 most critical files/modules with:
- Their specific purpose and responsibility
- How they fit into the overall architecture
- Key functions or classes they contain

## TECHNOLOGY STACK
Provide a detailed breakdown:
- **Languages**: Primary and secondary languages used
- **Frameworks**: Main frameworks and their versions (if detected)
- **Libraries**: Key dependencies and their purposes
- **Infrastructure**: Docker, CI/CD, cloud services, databases
- **Development Tools**: Testing frameworks, linters, build tools

## CODE QUALITY & MATURITY
Assess:
- Code organization and structure quality
- Testing coverage and strategy
- Documentation completeness
- DevOps maturity (CI/CD, containerization)
- Security practices (if observable)

## ONBOARDING ROADMAP
Provide a step-by-step guide for new developers:
1. **First 30 minutes**: What to read and understand
2. **First day**: How to set up and run the project
3. **First week**: Key concepts and patterns to master
4. **Pro tips**: Common pitfalls and best practices

## COMPLEXITY & SCALABILITY ASSESSMENT
- **Complexity Score**: X/10 with detailed justification
- **Scalability**: How well the architecture scales
- **Maintainability**: How easy it is to modify and extend
- **Technical Debt**: Observable issues or areas for improvement

Be specific, insightful, and provide actionable information. Use the actual file names and code patterns you observe."""

    audit_data = smart_audit(owner, repo, file_list)
    summary = await ask_watsonx(prompt, context, audit_data["scores"])

    return {
        "owner": owner,
        "repo": repo,
        "total_files": len(file_list),
        "file_tree": file_list,
        "summary": summary,
        "quick_wins": audit_data["quick_wins"],
        "scores": audit_data["scores"]
    }

@app.post("/ask")
async def ask_question(request: QuestionRequest):
    """Answer questions with deep contextual understanding."""
    owner, repo = parse_github_url(request.github_url)
    if not owner:
        return {"error": "Invalid GitHub URL"}

    file_list = get_repo_tree(owner, repo)
    context = build_context(owner, repo, file_list)

    prompt = f"""You are CodeCompass, an expert software architect with deep knowledge of software engineering principles, design patterns, and best practices.

{context}

A developer has asked the following question about this repository. Provide a comprehensive, accurate answer that:
1. Directly addresses their question
2. References specific files and code patterns from the repository
3. Explains the "why" behind implementation choices
4. Provides context about how it fits into the overall architecture
5. Suggests related areas they might want to explore

Question: {request.question}

Provide a detailed, professional answer with code references where applicable:"""

    answer = await ask_watsonx(prompt, context)
    return {"answer": answer}

@app.get("/file")
async def get_file(owner: str, repo: str, path: str):
    """Get content of a specific file from the repository."""
    content = get_file_content(owner, repo, path)
    if not content:
        return {"error": "Could not fetch file content"}
    return {"content": content, "path": path}

@app.get("/health")
def health():
    return {"status": "CodeCompass is running 🧭"}