# =============================================================
# CodeCompass - Analyzer Test Suite
# Generated by IBM watsonx.ai (Bob) | IBM Bob Dev Day Hackathon
# =============================================================

import pytest
from unittest.mock import patch, MagicMock
from analyzer import (
    parse_github_url,
    analyze_file_structure,
    get_key_files,
    smart_audit,
    build_context,
)


# ─── parse_github_url ────────────────────────────────────────

def test_parse_github_url_standard():
    owner, repo = parse_github_url("https://github.com/facebook/react")
    assert owner == "facebook"
    assert repo == "react"

def test_parse_github_url_trailing_slash():
    owner, repo = parse_github_url("https://github.com/openai/openai-python/")
    assert owner == "openai"
    assert repo == "openai-python"

def test_parse_github_url_dot_git():
    owner, repo = parse_github_url("https://github.com/django/django.git")
    assert owner == "django"
    assert repo == "django"

def test_parse_github_url_invalid():
    owner, repo = parse_github_url("not-a-url")
    assert owner is None
    assert repo is None

def test_parse_github_url_bare_path():
    owner, repo = parse_github_url("torvalds/linux")
    assert owner == "torvalds"
    assert repo == "linux"


# ─── analyze_file_structure ──────────────────────────────────

SAMPLE_FILES = [
    "README.md",
    "main.py",
    "analyzer.py",
    "requirements.txt",
    "Dockerfile",
    "tests/test_main.py",
    "tests/test_analyzer.py",
    ".github/workflows/ci.yml",
    "src/utils.py",
    "src/models.py",
    "static/index.html",
    "static/style.css",
]

def test_analyze_file_structure_has_tests():
    result = analyze_file_structure(SAMPLE_FILES)
    assert result["has_tests"] is True

def test_analyze_file_structure_has_docs():
    result = analyze_file_structure(SAMPLE_FILES)
    assert result["has_docs"] is True

def test_analyze_file_structure_has_ci():
    result = analyze_file_structure(SAMPLE_FILES)
    assert result["has_ci"] is True

def test_analyze_file_structure_has_docker():
    result = analyze_file_structure(SAMPLE_FILES)
    assert result["has_docker"] is True

def test_analyze_file_structure_has_frontend():
    result = analyze_file_structure(SAMPLE_FILES)
    assert result["has_frontend"] is True

def test_analyze_file_structure_has_backend():
    result = analyze_file_structure(SAMPLE_FILES)
    assert result["has_backend"] is True

def test_analyze_file_structure_extension_counts():
    result = analyze_file_structure(SAMPLE_FILES)
    assert "py" in result["extensions"]
    assert result["extensions"]["py"] >= 2

def test_analyze_file_structure_empty():
    result = analyze_file_structure([])
    assert result["has_tests"] is False
    assert result["total_directories"] == 0


# ─── get_key_files ───────────────────────────────────────────

def test_get_key_files_readme_first():
    files = ["src/utils.py", "README.md", "main.py", "tests/test_main.py"]
    key = get_key_files(files)
    assert "README.md" in key
    assert key.index("README.md") < key.index("src/utils.py") or "src/utils.py" not in key

def test_get_key_files_limits_output():
    files = [f"file_{i}.py" for i in range(100)]
    files.append("README.md")
    key = get_key_files(files)
    assert len(key) <= 15

def test_get_key_files_prefers_entry_points():
    files = ["README.md", "main.py", "utils/helper.py", "requirements.txt"]
    key = get_key_files(files)
    assert "main.py" in key
    assert "README.md" in key


# ─── smart_audit ─────────────────────────────────────────────

def test_smart_audit_scores_present():
    with patch("analyzer.get_file_content", return_value="fastapi\nhttpx"):
        result = smart_audit("owner", "repo", SAMPLE_FILES)
    assert "scores" in result
    scores = result["scores"]
    assert "test_score" in scores
    assert "devops_score" in scores
    assert "docs_score" in scores
    assert "structure_score" in scores
    assert "security_score" in scores

def test_smart_audit_scores_in_range():
    with patch("analyzer.get_file_content", return_value="fastapi"):
        result = smart_audit("owner", "repo", SAMPLE_FILES)
    for key, val in result["scores"].items():
        assert 0.0 <= val <= 10.0, f"{key} out of range: {val}"

def test_smart_audit_no_tests_detected():
    files_no_tests = ["README.md", "main.py", "requirements.txt", "Dockerfile"]
    with patch("analyzer.get_file_content", return_value="fastapi"):
        result = smart_audit("owner", "repo", files_no_tests)
    assert result["scores"]["test_score"] == 0.0

def test_smart_audit_quick_wins_for_missing_items():
    minimal_files = ["main.py"]
    with patch("analyzer.get_file_content", return_value=""):
        result = smart_audit("owner", "repo", minimal_files)
    titles = [w["title"] for w in result["quick_wins"]]
    assert any("README" in t for t in titles)
    assert any("test" in t.lower() or "Test" in t for t in titles)

def test_smart_audit_env_file_detected():
    files_with_env = SAMPLE_FILES + [".env"]
    with patch("analyzer.get_file_content", return_value=""):
        result = smart_audit("owner", "repo", files_with_env)
    titles = [w["title"] for w in result["quick_wins"]]
    assert any(".env" in t or "CRITICAL" in t for t in titles)


# ─── get_repo_tree error handling ────────────────────────────

def test_get_repo_tree_rate_limit():
    from analyzer import get_repo_tree
    mock_response = MagicMock()
    mock_response.status_code = 403
    mock_response.headers = {"X-RateLimit-Remaining": "0"}
    with patch("analyzer.requests.get", return_value=mock_response):
        with pytest.raises(ValueError, match="RATE_LIMIT"):
            get_repo_tree("owner", "repo")

def test_get_repo_tree_not_found():
    from analyzer import get_repo_tree
    mock_response = MagicMock()
    mock_response.status_code = 404
    with patch("analyzer.requests.get", return_value=mock_response):
        with pytest.raises(ValueError, match="NOT_FOUND"):
            get_repo_tree("owner", "repo")
