# =============================================================
# CodeCompass - API Endpoint Test Suite
# Generated by IBM watsonx.ai (Bob) | IBM Bob Dev Day Hackathon
# =============================================================

import pytest
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient
from main import app, generate_local_analysis, strip_emojis

client = TestClient(app)


# --- Health endpoint -----------------------------------------

def test_health_check():
    response = client.get("/health")
    assert response.status_code == 200
    assert "status" in response.json()

def test_index_returns_html():
    response = client.get("/")
    assert response.status_code == 200
    assert "text/html" in response.headers["content-type"]


# --- /analyze endpoint ---------------------------------------

def test_analyze_invalid_url():
    response = client.post("/analyze", json={"github_url": "not-a-valid-url"})
    assert response.status_code == 200
    data = response.json()
    assert "error" in data

def test_analyze_missing_body():
    response = client.post("/analyze", json={})
    assert response.status_code == 422

def test_analyze_rate_limit_error():
    with patch("main.get_repo_tree", side_effect=ValueError("RATE_LIMIT: GitHub API rate limit exceeded.")):
        response = client.post("/analyze", json={"github_url": "https://github.com/owner/repo"})
    data = response.json()
    assert "error" in data
    assert "rate limit" in data["error"].lower()

def test_analyze_not_found_error():
    with patch("main.get_repo_tree", side_effect=ValueError("NOT_FOUND: Repository not found.")):
        response = client.post("/analyze", json={"github_url": "https://github.com/owner/repo"})
    data = response.json()
    assert "error" in data
    assert "not found" in data["error"].lower()

def test_analyze_empty_repo():
    with patch("main.get_repo_tree", return_value=[]):
        response = client.post("/analyze", json={"github_url": "https://github.com/owner/repo"})
    data = response.json()
    assert "error" in data


# --- /ask endpoint -------------------------------------------

def test_ask_invalid_url():
    response = client.post("/ask", json={"github_url": "bad-url", "question": "What is this?"})
    assert response.status_code == 200
    data = response.json()
    assert "error" in data

def test_ask_missing_question():
    response = client.post("/ask", json={"github_url": "https://github.com/owner/repo"})
    assert response.status_code == 422

def test_ask_missing_body():
    response = client.post("/ask", json={})
    assert response.status_code == 422


# --- /file endpoint ------------------------------------------

def test_file_not_found():
    with patch("main.get_file_content", return_value=""):
        response = client.get("/file?owner=owner&repo=repo&path=nonexistent.py")
    data = response.json()
    assert "error" in data

def test_file_success():
    with patch("main.get_file_content", return_value="print('hello')"):
        response = client.get("/file?owner=owner&repo=repo&path=main.py")
    data = response.json()
    assert "content" in data
    assert data["path"] == "main.py"


# --- strip_emojis --------------------------------------------

def test_strip_emojis_removes_emoji():
    result = strip_emojis("Hello World")
    assert "Hello" in result
    assert "World" in result

def test_strip_emojis_clean_text_unchanged():
    text = "This is clean text with no emojis."
    assert strip_emojis(text) == text

def test_strip_emojis_empty_string():
    assert strip_emojis("") == ""


# --- generate_local_analysis ---------------------------------

def test_generate_local_analysis_architecture():
    context = "Primary Language: Python\nHas Tests: checkmark\nHas Docker: checkmark\nHas CI/CD: x\nArchitecture: Full-stack"
    scores = {"structure_score": 8, "test_score": 7, "docs_score": 6, "devops_score": 5, "security_score": 9}
    result = generate_local_analysis("analyze the Architecture", context, scores)
    assert "Architecture" in result
    assert "Python" in result

def test_generate_local_analysis_fallback():
    result = generate_local_analysis("random question", "", {})
    assert isinstance(result, str)
    assert len(result) > 0
